verion: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: api_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: apidb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: